/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica.screens;

import br.edu.imepac.clinica.screens.especialidades.EspecialidadeAddForm;
import br.edu.imepac.clinica.screens.especialidades.EspecialidadeListForm;
import br.edu.imepac.clinica.screens.medicos.MedicoAddForm;
import br.edu.imepac.clinica.screens.medicos.MedicoListForm;
import br.edu.imepac.clinica.screens.medicos.MedicoUpdateForm;

/**
 *
 * @author evertonhf
 */
public class MainMenu extends BaseScreen {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        ajustarLarguraTela();
        posicionarTopo(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        especialidadeMenu = new javax.swing.JMenu();
        cadastrarEspecialidade = new javax.swing.JMenuItem();
        listarEspecialidade = new javax.swing.JMenuItem();
        medicoMenu = new javax.swing.JMenu();
        cadastrarMedico = new javax.swing.JMenuItem();
        listarMedico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        especialidadeMenu.setText("Especialidades");

        cadastrarEspecialidade.setText("Cadastrar");
        cadastrarEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEspecialidadeActionPerformed(evt);
            }
        });
        especialidadeMenu.add(cadastrarEspecialidade);

        listarEspecialidade.setText("Listagem");
        listarEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarEspecialidadeActionPerformed(evt);
            }
        });
        especialidadeMenu.add(listarEspecialidade);

        jMenuBar1.add(especialidadeMenu);

        medicoMenu.setText("Medicos");

        cadastrarMedico.setText("Cadastrar");
        cadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarMedicoActionPerformed(evt);
            }
        });
        medicoMenu.add(cadastrarMedico);

        listarMedico.setText("Listagem");
        listarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMedicoActionPerformed(evt);
            }
        });
        medicoMenu.add(listarMedico);

        jMenuBar1.add(medicoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEspecialidadeActionPerformed
        EspecialidadeAddForm especialidadeAddForm = new EspecialidadeAddForm();
        especialidadeAddForm.pack();
        especialidadeAddForm.setVisible(true);
    }//GEN-LAST:event_cadastrarEspecialidadeActionPerformed

    private void listarEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarEspecialidadeActionPerformed
       EspecialidadeListForm especialidadeListForm = new EspecialidadeListForm();
       especialidadeListForm.pack();
       especialidadeListForm.setVisible(true);
    }//GEN-LAST:event_listarEspecialidadeActionPerformed

    private void cadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarMedicoActionPerformed
        MedicoAddForm medicoAddForm = new MedicoAddForm();
        medicoAddForm.pack();
        medicoAddForm.setVisible(true);
    }//GEN-LAST:event_cadastrarMedicoActionPerformed

    private void listarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMedicoActionPerformed
        MedicoListForm medicoListForm = new MedicoListForm();
        medicoListForm.pack();
        medicoListForm.setVisible(true);
    }//GEN-LAST:event_listarMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarEspecialidade;
    private javax.swing.JMenuItem cadastrarMedico;
    private javax.swing.JMenu especialidadeMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listarEspecialidade;
    private javax.swing.JMenuItem listarMedico;
    private javax.swing.JMenu medicoMenu;
    // End of variables declaration//GEN-END:variables
}
